--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'WIN1252';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: tasks_attachment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_attachment (
    id bigint NOT NULL,
    file character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    task_id bigint NOT NULL,
    uploaded_by_id integer NOT NULL
);


ALTER TABLE public.tasks_attachment OWNER TO postgres;

--
-- Name: tasks_attachment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_attachment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_attachment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_comment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_comment (
    id bigint NOT NULL,
    comment text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    task_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.tasks_comment OWNER TO postgres;

--
-- Name: tasks_comment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_comment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_comment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_notification; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_notification (
    id bigint NOT NULL,
    message text NOT NULL,
    type character varying(20) NOT NULL,
    sent_at timestamp with time zone NOT NULL,
    is_read boolean NOT NULL,
    task_id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.tasks_notification OWNER TO postgres;

--
-- Name: tasks_notification_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_notification ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_notification_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_task; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_task (
    id bigint NOT NULL,
    title character varying(200) NOT NULL,
    description text NOT NULL,
    deadline timestamp with time zone NOT NULL,
    priority character varying(10) NOT NULL,
    status character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    assigned_by_id integer NOT NULL,
    assigned_to_id integer NOT NULL,
    created_by_id integer NOT NULL
);


ALTER TABLE public.tasks_task OWNER TO postgres;

--
-- Name: tasks_task_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_task ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_task_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tasks_taskhistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.tasks_taskhistory (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    "timestamp" timestamp with time zone NOT NULL,
    assigned_by_id integer NOT NULL,
    assigned_to_id integer NOT NULL,
    task_id bigint NOT NULL
);


ALTER TABLE public.tasks_taskhistory OWNER TO postgres;

--
-- Name: tasks_taskhistory_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.tasks_taskhistory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tasks_taskhistory_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add task	7	add_task
26	Can change task	7	change_task
27	Can delete task	7	delete_task
28	Can view task	7	view_task
29	Can add task history	8	add_taskhistory
30	Can change task history	8	change_taskhistory
31	Can delete task history	8	delete_taskhistory
32	Can view task history	8	view_taskhistory
33	Can add comment	9	add_comment
34	Can change comment	9	change_comment
35	Can delete comment	9	delete_comment
36	Can view comment	9	view_comment
37	Can add attachment	10	add_attachment
38	Can change attachment	10	change_attachment
39	Can delete attachment	10	delete_attachment
40	Can view attachment	10	view_attachment
41	Can add notification	11	add_notification
42	Can change notification	11	change_notification
43	Can delete notification	11	delete_notification
44	Can view notification	11	view_notification
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$870000$R2YfmyR59zcVHGlylmefle$nkFjCu/TSHx0YPSk6e9cQiazrp/J7E3AEVRFwMb8IDM=	2025-04-17 15:02:07.347666+05:30	t	Abhi			thejuices.co@gmail.com	t	t	2025-04-16 12:45:18.011311+05:30
3	pbkdf2_sha256$870000$T0Z1TpNdQCcdSPPuKLbegs$RXYc5Ofln2zv6xg8ptaEc9MP98DSX4mfVtMSwiimcpg=	2025-04-17 15:10:50.48993+05:30	t	Aayushi				t	t	2025-04-17 15:09:00+05:30
2	pbkdf2_sha256$870000$qDgSpRmzEi4OWkuyxF0CE2$KVncZsPnPrdwZnzQLzJuUkVdtezI37zGwGnKfYnaZ6A=	2025-04-18 11:54:40.582076+05:30	t	Naveen				t	t	2025-04-16 12:47:38+05:30
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-04-16 12:47:39.592353+05:30	2	Naveen	1	[{"added": {}}]	4	1
2	2025-04-16 12:47:56.779944+05:30	2	Naveen	2	[]	4	1
3	2025-04-16 12:48:16.957047+05:30	2	Naveen	2	[{"changed": {"fields": ["Staff status", "Superuser status"]}}]	4	1
4	2025-04-17 15:09:01.427188+05:30	3	Aayushi	1	[{"added": {}}]	4	1
5	2025-04-17 15:09:29.306531+05:30	3	Aayushi	2	[{"changed": {"fields": ["Staff status", "Superuser status"]}}]	4	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	tasks	task
8	tasks	taskhistory
9	tasks	comment
10	tasks	attachment
11	tasks	notification
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-04-16 12:43:43.895626+05:30
2	auth	0001_initial	2025-04-16 12:43:44.110908+05:30
3	admin	0001_initial	2025-04-16 12:43:44.176795+05:30
4	admin	0002_logentry_remove_auto_add	2025-04-16 12:43:44.197897+05:30
5	admin	0003_logentry_add_action_flag_choices	2025-04-16 12:43:44.212226+05:30
6	contenttypes	0002_remove_content_type_name	2025-04-16 12:43:44.244398+05:30
7	auth	0002_alter_permission_name_max_length	2025-04-16 12:43:44.263454+05:30
8	auth	0003_alter_user_email_max_length	2025-04-16 12:43:44.278677+05:30
9	auth	0004_alter_user_username_opts	2025-04-16 12:43:44.381573+05:30
10	auth	0005_alter_user_last_login_null	2025-04-16 12:43:44.402768+05:30
11	auth	0006_require_contenttypes_0002	2025-04-16 12:43:44.406043+05:30
12	auth	0007_alter_validators_add_error_messages	2025-04-16 12:43:44.428436+05:30
13	auth	0008_alter_user_username_max_length	2025-04-16 12:43:44.455005+05:30
14	auth	0009_alter_user_last_name_max_length	2025-04-16 12:43:44.477799+05:30
15	auth	0010_alter_group_name_max_length	2025-04-16 12:43:44.502577+05:30
16	auth	0011_update_proxy_permissions	2025-04-16 12:43:44.522104+05:30
17	auth	0012_alter_user_first_name_max_length	2025-04-16 12:43:44.543852+05:30
18	sessions	0001_initial	2025-04-16 12:43:47.720228+05:30
19	tasks	0001_initial	2025-04-16 12:43:48.179656+05:30
20	tasks	0002_alter_task_deadline	2025-04-18 11:49:25.481827+05:30
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
6bp3mmhzdxdpvj2iqn5sjuj1dcrrqxnx	.eJxVjDsOgzAQRO_iOrLW-EvK9JzB8u7agSQyEoYqyt0DEkVSjTTvzbxFTNs6xq3lJU4srkKJy2-HiZ65HoAfqd5nSXNdlwnlociTNjnMnF-30_07GFMb93UHbCG5DtkWa3tANCY4CLSnR0WkNPtie-NIE3jdQQEsRocClL1j8fkC0J03kg:1u4x0c:V-qLiigcdoy1Oe9HfjdLymRM5QhhcTQ2pvG2goPT9dE	2025-04-30 12:46:34.229575+05:30
le9qobarwakrozbp8xadb3lkym8qs7mq	.eJxVjEEOwiAQRe_C2hCgwgwu3fcMhGFAqoYmpV0Z765NutDtf-_9lwhxW2vYel7CxOIijDj9bhTTI7cd8D222yzT3NZlIrkr8qBdjjPn5_Vw_w5q7PVbu6JpyCkpdlgUk0Fg7TMAOOVYJ4aCQIjZG4WewBYLZ61UckwDohXvD-0UN5U:1u4xLO:SftzRBsAvwk6Gbyord9W-J6qpFZAIpwmlxgSs16Aoik	2025-04-30 13:08:02.908834+05:30
ukuobkl42r2nw0cbwlxrjt8s6y3dyxkm	.eJxVjDsOgzAQRO_iOrLW-EvK9JzB8u7agSQyEoYqyt0DEkVSjTTvzbxFTNs6xq3lJU4srkKJy2-HiZ65HoAfqd5nSXNdlwnlociTNjnMnF-30_07GFMb93UHbCG5DtkWa3tANCY4CLSnR0WkNPtie-NIE3jdQQEsRocClL1j8fkC0J03kg:1u5LbL:d7AxhOTXv_gLTB7rSJSLfQv58BZCc9Klty6uV8iI3fo	2025-05-01 15:02:07.397066+05:30
vsnddtkbkh37kua5l32kd76l6wuup9cl	.eJxVjMsOwiAQRf-FtSFAeY1L934DGWCQqoGktCvjv2uTLnR7zzn3xQJuaw3boCXMmZ3ZxE6_W8T0oLaDfMd26zz1ti5z5LvCDzr4tWd6Xg7376DiqN_ak5YqTVDQEGhnko9ZK0HgrEFAbWWRqGwBa7xQoIsp0TmFmvIkQBB7fwDTqjdc:1u5Ljm:sxilJinEEJYn0_lW1wl0YKIJHfyGgkWThZmCsRq7dOQ	2025-05-01 15:10:50.492919+05:30
rynb0lnm5777f8lkp5cye3vpdoe9jz7v	.eJxVjDsOwjAQBe_iGlmrXTshlPScwXrrDwkgR8qnirg7REoB7ZuZt5mAdenDOucpDMlcDJvT76aIz1x3kB6o99HGsS7ToHZX7EFnextTfl0P9--gx9x_a-K2CLoWPndQ4SYytdIV5aSxuIIEON-QeCfnrA7KIIfIOQmJknl_APKLOGc:1u5f9U:ojXi355k_W0_GEjD4nnLUHYxWRxAYeFqvnicUT9lxrg	2025-05-02 11:54:40.588864+05:30
\.


--
-- Data for Name: tasks_attachment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_attachment (id, file, created_at, task_id, uploaded_by_id) FROM stdin;
1	attachments/Task_Management.pdf	2025-04-16 13:13:49.642148+05:30	1	2
\.


--
-- Data for Name: tasks_comment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_comment (id, comment, created_at, task_id, user_id) FROM stdin;
1	Web service is created\r\n	2025-04-16 13:37:06.684205+05:30	1	1
2	Nice Progress	2025-04-17 15:04:58.553438+05:30	1	1
\.


--
-- Data for Name: tasks_notification; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_notification (id, message, type, sent_at, is_read, task_id, user_id) FROM stdin;
\.


--
-- Data for Name: tasks_task; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_task (id, title, description, deadline, priority, status, created_at, updated_at, assigned_by_id, assigned_to_id, created_by_id) FROM stdin;
1	Task Tracker Creation	Create a Task Tracker Web service and .apk\r\nNeed to add Employee data\r\n	2025-04-18 03:30:00+05:30	High	In Progress	2025-04-16 12:50:22.02572+05:30	2025-04-17 15:06:04.826813+05:30	1	2	1
2	Office Organising	List Down all the requirements for Office and Events as well 	2025-04-20 03:30:00+05:30	High	Pending	2025-04-17 15:14:09.885394+05:30	2025-04-17 15:14:09.885452+05:30	1	3	1
\.


--
-- Data for Name: tasks_taskhistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.tasks_taskhistory (id, status, "timestamp", assigned_by_id, assigned_to_id, task_id) FROM stdin;
1	Pending	2025-04-16 12:50:22.04006+05:30	1	2	1
2	Pending	2025-04-17 15:04:15.90265+05:30	1	2	1
3	In Progress	2025-04-17 15:06:04.829584+05:30	2	2	1
4	Pending	2025-04-17 15:14:09.894166+05:30	1	3	2
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 5, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 20, true);


--
-- Name: tasks_attachment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_attachment_id_seq', 1, true);


--
-- Name: tasks_comment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_comment_id_seq', 2, true);


--
-- Name: tasks_notification_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_notification_id_seq', 1, false);


--
-- Name: tasks_task_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_task_id_seq', 3, true);


--
-- Name: tasks_taskhistory_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.tasks_taskhistory_id_seq', 5, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: tasks_attachment tasks_attachment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_attachment
    ADD CONSTRAINT tasks_attachment_pkey PRIMARY KEY (id);


--
-- Name: tasks_comment tasks_comment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_comment
    ADD CONSTRAINT tasks_comment_pkey PRIMARY KEY (id);


--
-- Name: tasks_notification tasks_notification_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_notification
    ADD CONSTRAINT tasks_notification_pkey PRIMARY KEY (id);


--
-- Name: tasks_task tasks_task_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_task
    ADD CONSTRAINT tasks_task_pkey PRIMARY KEY (id);


--
-- Name: tasks_taskhistory tasks_taskhistory_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_taskhistory
    ADD CONSTRAINT tasks_taskhistory_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: tasks_attachment_task_id_4e218594; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_attachment_task_id_4e218594 ON public.tasks_attachment USING btree (task_id);


--
-- Name: tasks_attachment_uploaded_by_id_cdf1e7a0; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_attachment_uploaded_by_id_cdf1e7a0 ON public.tasks_attachment USING btree (uploaded_by_id);


--
-- Name: tasks_comment_task_id_8e8bc4fe; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_comment_task_id_8e8bc4fe ON public.tasks_comment USING btree (task_id);


--
-- Name: tasks_comment_user_id_13cb3eb1; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_comment_user_id_13cb3eb1 ON public.tasks_comment USING btree (user_id);


--
-- Name: tasks_notification_task_id_0e908a3c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_notification_task_id_0e908a3c ON public.tasks_notification USING btree (task_id);


--
-- Name: tasks_notification_user_id_c1e4e074; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_notification_user_id_c1e4e074 ON public.tasks_notification USING btree (user_id);


--
-- Name: tasks_task_assigned_by_id_e64b5ab4; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_assigned_by_id_e64b5ab4 ON public.tasks_task USING btree (assigned_by_id);


--
-- Name: tasks_task_assigned_to_id_e8821f61; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_assigned_to_id_e8821f61 ON public.tasks_task USING btree (assigned_to_id);


--
-- Name: tasks_task_created_by_id_1345568a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_task_created_by_id_1345568a ON public.tasks_task USING btree (created_by_id);


--
-- Name: tasks_taskhistory_assigned_by_id_e468a52a; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_taskhistory_assigned_by_id_e468a52a ON public.tasks_taskhistory USING btree (assigned_by_id);


--
-- Name: tasks_taskhistory_assigned_to_id_fdc1dae7; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_taskhistory_assigned_to_id_fdc1dae7 ON public.tasks_taskhistory USING btree (assigned_to_id);


--
-- Name: tasks_taskhistory_task_id_3c50c29d; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX tasks_taskhistory_task_id_3c50c29d ON public.tasks_taskhistory USING btree (task_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_attachment tasks_attachment_task_id_4e218594_fk_tasks_task_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_attachment
    ADD CONSTRAINT tasks_attachment_task_id_4e218594_fk_tasks_task_id FOREIGN KEY (task_id) REFERENCES public.tasks_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_attachment tasks_attachment_uploaded_by_id_cdf1e7a0_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_attachment
    ADD CONSTRAINT tasks_attachment_uploaded_by_id_cdf1e7a0_fk_auth_user_id FOREIGN KEY (uploaded_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_comment tasks_comment_task_id_8e8bc4fe_fk_tasks_task_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_comment
    ADD CONSTRAINT tasks_comment_task_id_8e8bc4fe_fk_tasks_task_id FOREIGN KEY (task_id) REFERENCES public.tasks_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_comment tasks_comment_user_id_13cb3eb1_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_comment
    ADD CONSTRAINT tasks_comment_user_id_13cb3eb1_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_notification tasks_notification_task_id_0e908a3c_fk_tasks_task_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_notification
    ADD CONSTRAINT tasks_notification_task_id_0e908a3c_fk_tasks_task_id FOREIGN KEY (task_id) REFERENCES public.tasks_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_notification tasks_notification_user_id_c1e4e074_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_notification
    ADD CONSTRAINT tasks_notification_user_id_c1e4e074_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_task tasks_task_assigned_by_id_e64b5ab4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_task
    ADD CONSTRAINT tasks_task_assigned_by_id_e64b5ab4_fk_auth_user_id FOREIGN KEY (assigned_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_task tasks_task_assigned_to_id_e8821f61_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_task
    ADD CONSTRAINT tasks_task_assigned_to_id_e8821f61_fk_auth_user_id FOREIGN KEY (assigned_to_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_task tasks_task_created_by_id_1345568a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_task
    ADD CONSTRAINT tasks_task_created_by_id_1345568a_fk_auth_user_id FOREIGN KEY (created_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_taskhistory tasks_taskhistory_assigned_by_id_e468a52a_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_taskhistory
    ADD CONSTRAINT tasks_taskhistory_assigned_by_id_e468a52a_fk_auth_user_id FOREIGN KEY (assigned_by_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_taskhistory tasks_taskhistory_assigned_to_id_fdc1dae7_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_taskhistory
    ADD CONSTRAINT tasks_taskhistory_assigned_to_id_fdc1dae7_fk_auth_user_id FOREIGN KEY (assigned_to_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tasks_taskhistory tasks_taskhistory_task_id_3c50c29d_fk_tasks_task_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.tasks_taskhistory
    ADD CONSTRAINT tasks_taskhistory_task_id_3c50c29d_fk_tasks_task_id FOREIGN KEY (task_id) REFERENCES public.tasks_task(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

